### ISSUE TITLE
User defined rpc.mqtt.topic is formatted wrong

### ISSUE THREAD

**Issue by mikejac** [mongoose-os-libs/rpc-mqtt#1]
Hi,

In file 'mgos_rpc_channel_mqtt.c', lines 32 and 33: (int) device_id.len should be removed. Like this:

    mg_asprintf(&topic, 0, "%s%s",
                get_cfg()->rpc.mqtt.topic, (wildcard ? "/#" : ""));

Regards,
 Michael

**Comment by rojer** [comment]
thank you! sent out a PR
